/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.Formularios;

import Beans.bCategoria;
import Controller.CategoriaController;
import Models.mCategoria;

/**
 *
 * @author USUARIO
 */
public class frmCategoria extends javax.swing.JPanel {

    /**
     * Creates new form frmCategoria
     */
    bCategoria bCategoria = new bCategoria();
    mCategoria mCategoria = new mCategoria();
    
    public frmCategoria() {
        initComponents();
        CategoriaController categoriaC = new CategoriaController(this, bCategoria, mCategoria);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuTbl = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategorias = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        SelectBuscar = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CATEGORIAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 5, 250, 40));

        tblCategorias.setBackground(new java.awt.Color(255, 255, 255));
        tblCategorias.setForeground(new java.awt.Color(0, 0, 0));
        tblCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "N°", "NOMBRE", "DESCRIPCIÓN", "ESTADO"
            }
        ));
        tblCategorias.setComponentPopupMenu(MenuTbl);
        tblCategorias.setRequestFocusEnabled(false);
        tblCategorias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblCategorias);
        if (tblCategorias.getColumnModel().getColumnCount() > 0) {
            tblCategorias.getColumnModel().getColumn(0).setMinWidth(0);
            tblCategorias.getColumnModel().getColumn(0).setMaxWidth(0);
            tblCategorias.getColumnModel().getColumn(1).setMinWidth(50);
            tblCategorias.getColumnModel().getColumn(1).setMaxWidth(50);
            tblCategorias.getColumnModel().getColumn(4).setMinWidth(150);
            tblCategorias.getColumnModel().getColumn(4).setMaxWidth(150);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 180, 900, 600));

        btnNuevo.setBackground(new java.awt.Color(0, 0, 102));
        btnNuevo.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("NUEVO");
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 90, 150, 50));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("BUSCAR:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 80, 50));

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setBorder(null);
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 350, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 350, 10));

        SelectBuscar.setBackground(new java.awt.Color(255, 255, 255));
        SelectBuscar.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        SelectBuscar.setForeground(new java.awt.Color(0, 0, 0));
        SelectBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOMBRE", "CONDICION" }));
        jPanel1.add(SelectBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 135, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 950, 800));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPopupMenu MenuTbl;
    public javax.swing.JComboBox<String> SelectBuscar;
    public javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable tblCategorias;
    public javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
