/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.Formularios;

import Controller.PrincipalController;

/**
 *
 * @author USUARIO
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        PrincipalController principalC = new PrincipalController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        panelImagenUser = new javax.swing.JPanel();
        ImagenUser = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        panelMenu1 = new javax.swing.JPanel();
        lblOp1 = new javax.swing.JButton();
        panelMenu2 = new javax.swing.JPanel();
        lblOp2 = new javax.swing.JButton();
        panelMenu3 = new javax.swing.JPanel();
        lblOp3 = new javax.swing.JButton();
        panelMenu4 = new javax.swing.JPanel();
        lblOp4 = new javax.swing.JButton();
        panelMenu5 = new javax.swing.JPanel();
        lblOp5 = new javax.swing.JButton();
        panelMenu6 = new javax.swing.JPanel();
        lblOp6 = new javax.swing.JButton();
        panelMenu7 = new javax.swing.JPanel();
        lblOp7 = new javax.swing.JButton();
        panelMenu8 = new javax.swing.JPanel();
        lblOp8 = new javax.swing.JButton();
        panelMenu9 = new javax.swing.JPanel();
        lblOp9 = new javax.swing.JButton();
        lblCargo = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        panelFecha = new javax.swing.JPanel();
        txtFecha = new javax.swing.JLabel();
        panelContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(0, 0, 102));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 80, 250, 10));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MI TIENDA");
        panelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 250, 50));

        panelImagenUser.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout panelImagenUserLayout = new javax.swing.GroupLayout(panelImagenUser);
        panelImagenUser.setLayout(panelImagenUserLayout);
        panelImagenUserLayout.setHorizontalGroup(
            panelImagenUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImagenUserLayout.createSequentialGroup()
                .addComponent(ImagenUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelImagenUserLayout.setVerticalGroup(
            panelImagenUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImagenUserLayout.createSequentialGroup()
                .addComponent(ImagenUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelMenu.add(panelImagenUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 150, 150));
        panelMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 300, 240, 10));

        panelMenu1.setBackground(new java.awt.Color(0, 0, 102));
        panelMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMenu1MousePressed(evt);
            }
        });

        lblOp1.setBackground(new java.awt.Color(0, 0, 102));
        lblOp1.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        lblOp1.setForeground(new java.awt.Color(255, 255, 255));
        lblOp1.setBorder(null);
        lblOp1.setContentAreaFilled(false);
        lblOp1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelMenu1Layout = new javax.swing.GroupLayout(panelMenu1);
        panelMenu1.setLayout(panelMenu1Layout);
        panelMenu1Layout.setHorizontalGroup(
            panelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOp1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelMenu1Layout.setVerticalGroup(
            panelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenu1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblOp1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelMenu.add(panelMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 250, 60));

        panelMenu2.setBackground(new java.awt.Color(0, 0, 102));
        panelMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMenu2MousePressed(evt);
            }
        });

        lblOp2.setBackground(new java.awt.Color(0, 0, 102));
        lblOp2.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        lblOp2.setForeground(new java.awt.Color(255, 255, 255));
        lblOp2.setBorder(null);
        lblOp2.setContentAreaFilled(false);
        lblOp2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelMenu2Layout = new javax.swing.GroupLayout(panelMenu2);
        panelMenu2.setLayout(panelMenu2Layout);
        panelMenu2Layout.setHorizontalGroup(
            panelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu2Layout.createSequentialGroup()
                .addComponent(lblOp2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMenu2Layout.setVerticalGroup(
            panelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu2Layout.createSequentialGroup()
                .addComponent(lblOp2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelMenu.add(panelMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 250, 60));

        panelMenu3.setBackground(new java.awt.Color(0, 0, 102));
        panelMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMenu3MousePressed(evt);
            }
        });

        lblOp3.setBackground(new java.awt.Color(0, 0, 102));
        lblOp3.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        lblOp3.setForeground(new java.awt.Color(255, 255, 255));
        lblOp3.setBorder(null);
        lblOp3.setContentAreaFilled(false);
        lblOp3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelMenu3Layout = new javax.swing.GroupLayout(panelMenu3);
        panelMenu3.setLayout(panelMenu3Layout);
        panelMenu3Layout.setHorizontalGroup(
            panelMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu3Layout.createSequentialGroup()
                .addComponent(lblOp3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMenu3Layout.setVerticalGroup(
            panelMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblOp3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        panelMenu.add(panelMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 250, -1));

        panelMenu4.setBackground(new java.awt.Color(0, 0, 102));
        panelMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMenu4MousePressed(evt);
            }
        });

        lblOp4.setBackground(new java.awt.Color(0, 0, 102));
        lblOp4.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        lblOp4.setForeground(new java.awt.Color(255, 255, 255));
        lblOp4.setBorder(null);
        lblOp4.setContentAreaFilled(false);
        lblOp4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelMenu4Layout = new javax.swing.GroupLayout(panelMenu4);
        panelMenu4.setLayout(panelMenu4Layout);
        panelMenu4Layout.setHorizontalGroup(
            panelMenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu4Layout.createSequentialGroup()
                .addComponent(lblOp4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMenu4Layout.setVerticalGroup(
            panelMenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu4Layout.createSequentialGroup()
                .addComponent(lblOp4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        panelMenu.add(panelMenu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 250, 60));

        panelMenu5.setBackground(new java.awt.Color(0, 0, 102));
        panelMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMenu5MousePressed(evt);
            }
        });

        lblOp5.setBackground(new java.awt.Color(0, 0, 102));
        lblOp5.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        lblOp5.setForeground(new java.awt.Color(255, 255, 255));
        lblOp5.setBorder(null);
        lblOp5.setContentAreaFilled(false);
        lblOp5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelMenu5Layout = new javax.swing.GroupLayout(panelMenu5);
        panelMenu5.setLayout(panelMenu5Layout);
        panelMenu5Layout.setHorizontalGroup(
            panelMenu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu5Layout.createSequentialGroup()
                .addComponent(lblOp5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMenu5Layout.setVerticalGroup(
            panelMenu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu5Layout.createSequentialGroup()
                .addComponent(lblOp5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        panelMenu.add(panelMenu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 250, -1));

        panelMenu6.setBackground(new java.awt.Color(0, 0, 102));
        panelMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMenu6MousePressed(evt);
            }
        });

        lblOp6.setBackground(new java.awt.Color(0, 0, 102));
        lblOp6.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        lblOp6.setForeground(new java.awt.Color(255, 255, 255));
        lblOp6.setBorder(null);
        lblOp6.setContentAreaFilled(false);
        lblOp6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOp6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblOp6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenu6Layout = new javax.swing.GroupLayout(panelMenu6);
        panelMenu6.setLayout(panelMenu6Layout);
        panelMenu6Layout.setHorizontalGroup(
            panelMenu6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu6Layout.createSequentialGroup()
                .addComponent(lblOp6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMenu6Layout.setVerticalGroup(
            panelMenu6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu6Layout.createSequentialGroup()
                .addComponent(lblOp6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelMenu.add(panelMenu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 250, -1));

        panelMenu7.setBackground(new java.awt.Color(0, 0, 102));
        panelMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMenu7MousePressed(evt);
            }
        });

        lblOp7.setBackground(new java.awt.Color(0, 0, 102));
        lblOp7.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        lblOp7.setForeground(new java.awt.Color(255, 255, 255));
        lblOp7.setBorder(null);
        lblOp7.setContentAreaFilled(false);
        lblOp7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelMenu7Layout = new javax.swing.GroupLayout(panelMenu7);
        panelMenu7.setLayout(panelMenu7Layout);
        panelMenu7Layout.setHorizontalGroup(
            panelMenu7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu7Layout.createSequentialGroup()
                .addComponent(lblOp7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMenu7Layout.setVerticalGroup(
            panelMenu7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblOp7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelMenu.add(panelMenu7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 250, -1));

        panelMenu8.setBackground(new java.awt.Color(0, 0, 102));
        panelMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMenu8MousePressed(evt);
            }
        });

        lblOp8.setBackground(new java.awt.Color(0, 0, 102));
        lblOp8.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        lblOp8.setForeground(new java.awt.Color(255, 255, 255));
        lblOp8.setBorder(null);
        lblOp8.setContentAreaFilled(false);
        lblOp8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelMenu8Layout = new javax.swing.GroupLayout(panelMenu8);
        panelMenu8.setLayout(panelMenu8Layout);
        panelMenu8Layout.setHorizontalGroup(
            panelMenu8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu8Layout.createSequentialGroup()
                .addComponent(lblOp8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMenu8Layout.setVerticalGroup(
            panelMenu8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu8Layout.createSequentialGroup()
                .addComponent(lblOp8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelMenu.add(panelMenu8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 250, -1));

        panelMenu9.setBackground(new java.awt.Color(0, 0, 102));
        panelMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMenu9MousePressed(evt);
            }
        });

        lblOp9.setBackground(new java.awt.Color(0, 0, 102));
        lblOp9.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        lblOp9.setForeground(new java.awt.Color(255, 255, 255));
        lblOp9.setBorder(null);
        lblOp9.setContentAreaFilled(false);
        lblOp9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelMenu9Layout = new javax.swing.GroupLayout(panelMenu9);
        panelMenu9.setLayout(panelMenu9Layout);
        panelMenu9Layout.setHorizontalGroup(
            panelMenu9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu9Layout.createSequentialGroup()
                .addComponent(lblOp9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMenu9Layout.setVerticalGroup(
            panelMenu9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu9Layout.createSequentialGroup()
                .addComponent(lblOp9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelMenu.add(panelMenu9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 800, 250, -1));

        lblCargo.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblCargo.setForeground(new java.awt.Color(255, 255, 255));
        lblCargo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelMenu.add(lblCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 250, 50));
        panelMenu.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 15, 15));

        jPanel1.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 980));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrar.setText("CERRAR");
        btnCerrar.setBorderPainted(false);
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        jPanel2.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1065, 15, 150, 50));

        lblUser.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel2.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 15, 400, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1250, 80));

        panelFecha.setBackground(new java.awt.Color(255, 255, 255));

        txtFecha.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout panelFechaLayout = new javax.swing.GroupLayout(panelFecha);
        panelFecha.setLayout(panelFechaLayout);
        panelFechaLayout.setHorizontalGroup(
            panelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFechaLayout.createSequentialGroup()
                .addContainerGap(715, Short.MAX_VALUE)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        panelFechaLayout.setVerticalGroup(
            panelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFechaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel1.add(panelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 1250, 40));

        panelContenido.setBackground(new java.awt.Color(255, 255, 255));
        panelContenido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelContenido.setFocusable(false);

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );

        jPanel1.add(panelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 1250, 860));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenu1MousePressed

    }//GEN-LAST:event_panelMenu1MousePressed

    private void panelMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenu2MousePressed

    }//GEN-LAST:event_panelMenu2MousePressed

    private void panelMenu3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenu3MousePressed

    }//GEN-LAST:event_panelMenu3MousePressed

    private void panelMenu4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenu4MousePressed

    }//GEN-LAST:event_panelMenu4MousePressed

    private void panelMenu5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenu5MousePressed

    }//GEN-LAST:event_panelMenu5MousePressed

    private void lblOp6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblOp6ActionPerformed

    }//GEN-LAST:event_lblOp6ActionPerformed

    private void panelMenu6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenu6MousePressed

    }//GEN-LAST:event_panelMenu6MousePressed

    private void panelMenu7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenu7MousePressed

    }//GEN-LAST:event_panelMenu7MousePressed

    private void panelMenu8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenu8MousePressed

    }//GEN-LAST:event_panelMenu8MousePressed

    private void panelMenu9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenu9MousePressed

    }//GEN-LAST:event_panelMenu9MousePressed

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked

    }//GEN-LAST:event_btnCerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel ImagenUser;
    public javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JLabel lblCargo;
    public javax.swing.JButton lblOp1;
    public javax.swing.JButton lblOp2;
    public javax.swing.JButton lblOp3;
    public javax.swing.JButton lblOp4;
    public javax.swing.JButton lblOp5;
    public javax.swing.JButton lblOp6;
    public javax.swing.JButton lblOp7;
    public javax.swing.JButton lblOp8;
    public javax.swing.JButton lblOp9;
    public javax.swing.JLabel lblUser;
    public javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelFecha;
    private javax.swing.JPanel panelImagenUser;
    private javax.swing.JPanel panelMenu;
    public javax.swing.JPanel panelMenu1;
    public javax.swing.JPanel panelMenu2;
    public javax.swing.JPanel panelMenu3;
    public javax.swing.JPanel panelMenu4;
    public javax.swing.JPanel panelMenu5;
    public javax.swing.JPanel panelMenu6;
    public javax.swing.JPanel panelMenu7;
    public javax.swing.JPanel panelMenu8;
    public javax.swing.JPanel panelMenu9;
    public javax.swing.JLabel txtFecha;
    public javax.swing.JLabel txtId;
    // End of variables declaration//GEN-END:variables
}
