/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.Formularios;

import Beans.bUsuario;
import Controller.UsuarioController;
import Models.mUsuario;
import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author USUARIO
 */
public class frmUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form frmUsuarios
     */
    bUsuario bUsuario = new bUsuario();
    mUsuario mUsuario = new mUsuario();

    public frmUsuarios() {
        initComponents();
//        UIManager.put("nimbusBlueGrey", new Color(0, 0, 102));
        UsuarioController usuarioC = new UsuarioController(this, bUsuario, mUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuTbl = new javax.swing.JPopupMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        SelectBuscar = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        tblUsuarios.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "N°", "NOMBRE", "TIPO DOCUMENTO", "DOCUMENTO", "DIRECCIÓN", "TELEFONO", "EMAIL", "CARGO", "CONDICION"
            }
        ));
        tblUsuarios.setComponentPopupMenu(MenuTbl);
        tblUsuarios.setDragEnabled(true);
        tblUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblUsuarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblUsuarios);
        if (tblUsuarios.getColumnModel().getColumnCount() > 0) {
            tblUsuarios.getColumnModel().getColumn(0).setMinWidth(0);
            tblUsuarios.getColumnModel().getColumn(0).setMaxWidth(0);
            tblUsuarios.getColumnModel().getColumn(1).setMinWidth(25);
            tblUsuarios.getColumnModel().getColumn(1).setMaxWidth(25);
            tblUsuarios.getColumnModel().getColumn(3).setMinWidth(120);
            tblUsuarios.getColumnModel().getColumn(3).setMaxWidth(120);
            tblUsuarios.getColumnModel().getColumn(4).setMinWidth(100);
            tblUsuarios.getColumnModel().getColumn(4).setMaxWidth(100);
            tblUsuarios.getColumnModel().getColumn(5).setMinWidth(200);
            tblUsuarios.getColumnModel().getColumn(5).setMaxWidth(200);
            tblUsuarios.getColumnModel().getColumn(6).setMinWidth(90);
            tblUsuarios.getColumnModel().getColumn(6).setMaxWidth(90);
            tblUsuarios.getColumnModel().getColumn(8).setMinWidth(120);
            tblUsuarios.getColumnModel().getColumn(8).setMaxWidth(120);
            tblUsuarios.getColumnModel().getColumn(9).setMinWidth(120);
            tblUsuarios.getColumnModel().getColumn(9).setMaxWidth(120);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 1210, 670));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USUARIOS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 210, 40));

        btnNuevo.setBackground(new java.awt.Color(0, 0, 102));
        btnNuevo.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("NUEVO");
        add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, 50));

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setBorder(null);
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 90, 350, 50));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("BUSCAR:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 80, 50));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 140, 350, 10));

        SelectBuscar.setBackground(new java.awt.Color(255, 255, 255));
        SelectBuscar.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        SelectBuscar.setForeground(new java.awt.Color(0, 0, 0));
        SelectBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOMBRE", "DOCUMENTO", "CARGO", "CONDICION" }));
        add(SelectBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 150, 50));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPopupMenu MenuTbl;
    public javax.swing.JComboBox<String> SelectBuscar;
    public javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable tblUsuarios;
    public javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
