/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views.Modal;

/**
 *
 * @author USUARIO
 */
public class ModalIngreso extends javax.swing.JDialog {

    /**
     * Creates new form ModalIngreso
     */
    public ModalIngreso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuTbl = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProveedor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtComprobante = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        btnAgregarProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        lblSubTotal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblIgv = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        txtIdIngreso = new javax.swing.JLabel();
        lblProveedor = new javax.swing.JLabel();
        lblComprobante = new javax.swing.JLabel();
        lblSerie = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("NUEVO INGRESO");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 250, 40));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("PROVEEDOR:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 200, 40));

        txtProveedor.setBackground(new java.awt.Color(255, 255, 255));
        txtProveedor.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtProveedor.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 350, 40));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("COMPROBANTE:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 90, 175, 40));

        txtComprobante.setBackground(new java.awt.Color(255, 255, 255));
        txtComprobante.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtComprobante.setForeground(new java.awt.Color(0, 0, 0));
        txtComprobante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOLETA", "FACTURA", "TICKET" }));
        jPanel1.add(txtComprobante, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 130, 175, 40));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("SERIE:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 90, 100, 40));

        txtSerie.setBackground(new java.awt.Color(255, 255, 255));
        txtSerie.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtSerie.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 130, 100, 40));

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("NUMERO:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 150, 40));

        txtNumero.setBackground(new java.awt.Color(255, 255, 255));
        txtNumero.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtNumero.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 150, 40));

        btnAgregarProducto.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnAgregarProducto.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarProducto.setText("AGREGAR PRODUCTO");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 110, 225, 60));

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "N°", "CODIGO", "PRODUCTO", "CATEGORIA", "CANT.", "PRECIO UNID.", "SUB TOTAL"
            }
        ));
        jScrollPane1.setViewportView(tblDetalle);
        if (tblDetalle.getColumnModel().getColumnCount() > 0) {
            tblDetalle.getColumnModel().getColumn(0).setMinWidth(0);
            tblDetalle.getColumnModel().getColumn(0).setMaxWidth(0);
            tblDetalle.getColumnModel().getColumn(1).setMinWidth(30);
            tblDetalle.getColumnModel().getColumn(1).setMaxWidth(30);
            tblDetalle.getColumnModel().getColumn(2).setMinWidth(120);
            tblDetalle.getColumnModel().getColumn(2).setMaxWidth(120);
            tblDetalle.getColumnModel().getColumn(5).setMinWidth(50);
            tblDetalle.getColumnModel().getColumn(5).setMaxWidth(50);
            tblDetalle.getColumnModel().getColumn(6).setMinWidth(120);
            tblDetalle.getColumnModel().getColumn(6).setMaxWidth(120);
            tblDetalle.getColumnModel().getColumn(7).setMinWidth(120);
            tblDetalle.getColumnModel().getColumn(7).setMaxWidth(120);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 1100, 350));

        lblSubTotal.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        lblSubTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubTotal.setText("0.00");
        lblSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 560, 150, 35));

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("SUB TOTAL:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 560, 150, 35));

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("IGV:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 600, 150, 35));

        lblIgv.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        lblIgv.setForeground(new java.awt.Color(0, 0, 0));
        lblIgv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIgv.setText("0.00");
        lblIgv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblIgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 600, 150, 35));

        jLabel10.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("TOTAL:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 640, 150, 35));

        lblTotal.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("0.00");
        lblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 640, 150, 35));

        btnGuardar.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 700, 200, 60));

        btnCancelar.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        btnCancelar.setText("CANCELAR");
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 700, 200, 60));
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 50, 50));
        jPanel1.add(txtIdIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 50, 50));

        lblProveedor.setBackground(new java.awt.Color(255, 255, 255));
        lblProveedor.setForeground(new java.awt.Color(0, 0, 0));
        lblProveedor.setText("jLabel1");
        jPanel1.add(lblProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 350, 40));

        lblComprobante.setBackground(new java.awt.Color(255, 255, 255));
        lblComprobante.setForeground(new java.awt.Color(0, 0, 0));
        lblComprobante.setText("jLabel6");
        jPanel1.add(lblComprobante, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 130, 175, 40));

        lblSerie.setBackground(new java.awt.Color(255, 255, 255));
        lblSerie.setForeground(new java.awt.Color(0, 0, 0));
        lblSerie.setText("jLabel9");
        jPanel1.add(lblSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 130, 100, 40));

        lblNumero.setBackground(new java.awt.Color(255, 255, 255));
        lblNumero.setForeground(new java.awt.Color(0, 0, 0));
        lblNumero.setText("jLabel11");
        jPanel1.add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1225, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModalIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModalIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModalIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModalIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModalIngreso dialog = new ModalIngreso(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPopupMenu MenuTbl;
    public javax.swing.JButton btnAgregarProducto;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblComprobante;
    public javax.swing.JLabel lblIgv;
    public javax.swing.JLabel lblNumero;
    public javax.swing.JLabel lblProveedor;
    public javax.swing.JLabel lblSerie;
    public javax.swing.JLabel lblSubTotal;
    public javax.swing.JLabel lblTitulo;
    public javax.swing.JLabel lblTotal;
    public javax.swing.JLabel lblUser;
    public javax.swing.JTable tblDetalle;
    public javax.swing.JComboBox<Object> txtComprobante;
    public javax.swing.JLabel txtIdIngreso;
    public javax.swing.JTextField txtNumero;
    public javax.swing.JComboBox<Object> txtProveedor;
    public javax.swing.JTextField txtSerie;
    // End of variables declaration//GEN-END:variables
}
